### ISSUE TITLE
jcenter() not supported

### ISSUE THREAD

**Issue by lucagiordano-visia** [BanDev/Xplosion#23]
Hi, since jcenter() is no longer supported, you need to move to mavenCentral(), otherwise if someone (like me) don't have jcenter() in his project, this exception will be thrown
`
What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsProductionDebug'.
> Could not resolve all files for configuration ':app:productionDebugCompileClasspath'.
   > Could not find pub.hanks:smallbang:1.2.2.
     Required by:
         project :app

`

I leave u this: https://jeroenmols.com/blog/2021/02/04/migratingjcenter/#:~:text=Migrating%20your%20app%20away%20from,also%20migrate%20all%20existing%20artifacts.

**Comment by russellbanks** [comment]
Hey, you're referencing SmallBang here that is still on JCenter(). Xplosion is a fork of SmallBang and is on MavenCentral. Follow the usage steps in the README to add this to your project. Let me know if you have any issues with this.
